server:
  port: 8090
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/feedapp
    password: 87df20a6b2a8440007b601cab55e15dd7b37a6a01add83e7cea97767adc3dea3
    username: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
        hbm2ddl:
          auto: update
security:
  firebase-props:
    database-url: ${FIREBASE_DATABASE}
    enable-strict-server-session: true
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-props:
    max-age-in-minutes: 7200
    http-only: false
    secure: false
    domain: ${CORS_DOMAIN}
    path: /
  allow-credentials: true
  allowed-origins:
    - https://${CORS_DOMAIN}
    - http://localhost:3000
    - http://localhost:5000
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /api/v1/session/login
    - /api/v1/polls
    - /api/v1/polls/*/vote
    - /api/v1/polls/public
    - /api/v1/polls/public/*
    - /api/v1/accounts
    - /api/v1/polls/create
  exposed-headers:
    - X-Xsrf-Token

logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: INFO
